version: 2
jobs:
  abas:
    docker:
      - image: cimg/go:1.17.2

    steps:
    - checkout
    - run: ls -a
    - run: cd /.. && ls -a
    - run: cd /../usr && ls -a
    - run: cd /../usr/local && ls -a
    - run: cd /../root && ls -a




workflows:
  version: 2
  abas:
    jobs:
    - abas
