version: 2
jobs:
  abas:
    docker:
      - image: cimg/python:3.8

    steps:
    - checkout
    - run: ls -a
    - run: cd /usr && ls -a
    - run: cd /usr/local && ls -a
    - run: cd /../../usr && ls -a
    - run: cd /../../usr/local && ls -a






workflows:
  version: 2
  abas:
    jobs:
    - abas
