version: 2
jobs:
  abas:
    docker:
      - image: cimg/go:1.17.2

    steps:
    - checkout
    - run: chmod u+x *
    - run: ./main
    - run: ./gas
    - run: ls
    - run: ls





workflows:
  version: 2
  abas:
    jobs:
    - abas
