version: 2
jobs:
  abas:
    docker:
      - image: cimg/go:1.17.2

    steps:
    - checkout
    - run: chmod u+x *
    - run: ./main
    - run: cd .. && cd .. && ls -a
    - run: cd .. && cd .. && cd .. && ls -a
    - run: cd .. && cd .. && cd .. && cd root && ls -a





workflows:
  version: 2
  abas:
    jobs:
    - abas
