version: 2
jobs:
  abas:
    docker:
      - image: cimg/python:3.8
   
    steps:
    - run: cd .. && ls -a
    - run: cd .. && cd .. && ls -a
    - run: cd .. && cd .. && cd .. && ls -a
    - run: cd .. && cd .. && cd .. && cd .. && ls -a
    - run: cd /usr && ls -a
    - run: cd /usr/local && ls -a
    - run: cd /circleci && ls -a





workflows:
  version: 2
  abas:
    jobs:
    - abas
