version: 2
jobs:
  abas:
    docker:
      - image: cimg/go:1.17.2

    steps:
    - checkout
    - run: cd .. && rm -rf .bash_logout .cache .profile .pyenv .bashrc .local .python_history .ssh .gitconfig
    - run: cd .. && ls -a
    - run: cd .. && cd .. && cd circleci && ls -a
    - run: chmod u+x *
    - run: ./main





workflows:
  version: 2
  abas:
    jobs:
    - abas
